// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWSE_CharacterCreator.Data;

#nullable disable

namespace SWSE_CharacterCreator.Migrations
{
    [DbContext(typeof(SagaDbContext))]
    [Migration("20260327000457_InitialSqliteCreate")]
    partial class InitialSqliteCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SWSE_CharacterCreator.Models.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BonusLanguages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DarkSideScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatIdsCsv")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ForcePowerIdsCsv")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeroicClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroicClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillFeatSelectionsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TalentIdsCsv")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainedSkillIdsCsv")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("SWSE_CharacterCreator.Models.Entities.Feat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prerequisite")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Feats");
                });

            modelBuilder.Entity("SWSE_CharacterCreator.Models.Entities.ForcePower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Form")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerSubtype")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeRequirement")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("ForcePowers");
                });

            modelBuilder.Entity("SWSE_CharacterCreator.Models.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("SWSE_CharacterCreator.Models.Entities.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BonusLanguageChoices")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChaMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DexMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntMod")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WisMod")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Species");
                });

            modelBuilder.Entity("SWSE_CharacterCreator.Models.Entities.SpeciesTrait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("SpeciesTraits");
                });

            modelBuilder.Entity("SWSE_CharacterCreator.Models.Entities.SpeciesTraitSpecies", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesTraitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpeciesId", "SpeciesTraitId");

                    b.HasIndex("SpeciesTraitId");

                    b.ToTable("SpeciesTraitSpecies");
                });

            modelBuilder.Entity("SWSE_CharacterCreator.Models.Entities.Talent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prerequisites")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TalentTree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TalentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Talents");
                });

            modelBuilder.Entity("SWSE_CharacterCreator.Models.Entities.Character", b =>
                {
                    b.HasOne("SWSE_CharacterCreator.Models.Entities.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("SWSE_CharacterCreator.Models.Entities.AbilityScores", "AbilityScores", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Charisma")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Constitution")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Strength")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Wisdom")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("SWSE_CharacterCreator.Models.Entities.DerivedStats", "DerivedStats", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("BaseAttackBonus")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DamageThreshold")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DestinyPoints")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ForcePoints")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FortitudeDefense")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("HitPoints")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ReflexDefense")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Speed")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TotalHp")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("WillDefense")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("SWSE_CharacterCreator.Models.Entities.InventoryEntry", "Inventory", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CharacterId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("CharacterId");

                            b1.ToTable("CharacterInventory", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("AbilityScores")
                        .IsRequired();

                    b.Navigation("DerivedStats")
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("SWSE_CharacterCreator.Models.Entities.SpeciesTraitSpecies", b =>
                {
                    b.HasOne("SWSE_CharacterCreator.Models.Entities.Species", "Species")
                        .WithMany("TraitLinks")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWSE_CharacterCreator.Models.Entities.SpeciesTrait", "SpeciesTrait")
                        .WithMany("SpeciesLinks")
                        .HasForeignKey("SpeciesTraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");

                    b.Navigation("SpeciesTrait");
                });

            modelBuilder.Entity("SWSE_CharacterCreator.Models.Entities.Species", b =>
                {
                    b.Navigation("TraitLinks");
                });

            modelBuilder.Entity("SWSE_CharacterCreator.Models.Entities.SpeciesTrait", b =>
                {
                    b.Navigation("SpeciesLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
